from enum import Enum
class Wood(Enum):
    INDIAN_ROSEWOOD = 'INDIAN ROSEWOOD' 
    BRAZILIAN_ROSEWOOD = 'BRAZILIAN ROSEWOOD'
    MAHOGANY = 'MAHOGANY' 
    MAPLE = 'MAPLE' 
    COCOBOLO = 'COCOBOLO'
    CEDAR = 'CEDAR'
    ADIRONDACK = 'ADIRONDACK'
    ALDER = 'ALDER'
    SITKA = 'SITKA'